language: node_js
node_js:
- 0.10.40
before_script:
- npm install -g gulp
script: gulp deploy
before_install:
- openssl aes-256-cbc -K $encrypted_29d4e76ebd60_key -iv $encrypted_29d4e76ebd60_iv
  -in secrets.tar.gz.enc -out secrets.tar.gz -d
- tar zxvf secrets.tar.gz
